Se actualiza modelo de datos para el método storage
lunasoft/SW-sdk-NetStandard pull request #25
Opened 2020-12-16 00:21 UTC by RICH-CD

Se actualiza modelo de datos para deserializar el objeto json

2020-12-16 00:32 UTC, JuanGamezSW commented
Yo hubiera agregado una UT del uso del método.

2020-12-16 00:33 UTC, JuanGamezSW requested changes
Sería posible agregar una UT?

2020-12-16 16:45 UTC, RICH-CD commented
> Sería posible agregar una UT?

Se hace un ajuste a UT para que detecte si regresa valores diferentes de null

2020-12-16 17:44 UTC, JuanGamezSW approved these changes

2020-12-17 20:37 UTC, alxcodes approved these changes

2021-06-17 18:30 UTC, DanielIxiguez approved these changes

2021-06-17 18:53 UTC, merged