feature/cancela22
lunasoft/SW-sdk-NetStandard pull request #30
Opened 2022-01-04 18:44 UTC by sadyanx

-Se actualiza metodos de cancelacion.
-Se actualiza la version.
-Se actualiza la BuildSettings con cuenta de pruebas.

2022-01-04 19:00 UTC, SwAeyrton commented
-Se actualiza metodos de cancelacion.
-Se actualiza la version.
-Se actualiza la BuildSettings con cuenta de pruebas.

2022-01-04 20:05 UTC, JuanGamezSW requested changes
Revisar las UT ya que hay muchas que estan fallando.

2022-01-05 05:31 UTC, SwAeyrton commented
> Revisar las UT ya que hay muchas que están fallando.
Corregido

2022-01-05 16:58 UTC, JuanGamezSW approved these changes

2022-01-05 21:40 UTC, merged