SMARTER-3281
lunasoft/SW-sdk-NetStandard pull request #36
Opened 2022-04-22 22:03 UTC by JeduardoMT

- Se agregan pruebas unitarias de diferentes escenarios de timbrado CFDI 4.0 de los diferentes métodos de timbrado disponibles en sw-sdk-netstandard
 - Se configura archivo YAML para que acepte proyectos .NET 6

2022-04-25 15:39 UTC, SwAeyrton approved these changes

2022-04-25 19:10 UTC, JuanGamezSW requested changes

2022-04-25 19:10 UTC, JuanGamezSW commented on test/sdk-test-CFDI40/Helpers/BuildSettings.cs
> +        public string Token = @"T2lYQ0t4L0RHVkR4dHZ5Nkk1VHNEakZ3Y0J4Nk9GODZuRyt4cE1wVm5tbXB3YVZxTHdOdHAwVXY2NTdJb1hkREtXTzE3dk9pMmdMdkFDR2xFWFVPUXpTUm9mTG1ySXdZbFNja3FRa0RlYURqbzdzdlI2UUx1WGJiKzViUWY
Mismo caso con el token.

2022-04-26 01:33 UTC, JeduardoMT commented on azure-pipelines.yml
> +  displayName: 'Use .NET Core sdk 2.1'
Me parece bien de una vez actualizar el proyecto

2022-04-26 01:34 UTC, JeduardoMT commented on test/sdk-test-CFDI40/Helpers/BuildSettings.cs
> +        public string User = "pruebas_ut@sw.com.mx";
De acuerdo por los datos sensibles que se muestran

2022-04-26 01:34 UTC, JeduardoMT commented on test/sdk-test-CFDI40/Helpers/BuildSettings.cs
> +        public string Token = @"T2lYQ0t4L0RHVkR4dHZ5Nkk1VHNEakZ3Y0J4Nk9GODZuRyt4cE1wVm5tbXB3YVZxTHdOdHAwVXY2NTdJb1hkREtXTzE3dk9pMmdMdkFDR2xFWFVPUXpTUm9mTG1ySXdZbFNja3FRa0RlYURqbzdzdlI2UUx1WGJiKzViUWY
De acuerdo por los datos sensibles que se muestran

2022-04-26 21:34 UTC, merged