Feature/ss133
lunasoft/SW-sdk-NetStandard pull request #43
Opened 2022-09-29 18:43 UTC by SwAeyrton

2022-09-29 19:01 UTC, marifersw approved these changes

2022-09-29 19:12 UTC, FerCarrilloM approved these changes

2022-09-29 20:39 UTC, ReyesSW approved these changes

2022-09-30 16:22 UTC, martinfnsw requested changes

2022-09-30 16:22 UTC, martinfnsw commented on src/sw-sdk/Services/Pdf/BasePdf.cs
> +        internal virtual async Task<PdfResponse> GeneratePdfAsync(string xml, string b64Logo, PdfTemplates templateId, string idUser, string idDealer, Dictionary<string, string> ObservacionesAdiciona
Lo veo bien pero el API pdf por default realiza la consulta al token y obtiene los id.

2022-09-30 22:27 UTC, martinfnsw approved these changes

2022-09-30 22:48 UTC, merged