Feature/naming conventions
lunasoft/SW-sdk-NetStandard pull request #74
Opened 2023-04-21 19:37 UTC by marifersw

2023-04-21 20:37 UTC, ReyesSW approved these changes

2023-04-21 23:25 UTC, SebastianSW approved these changes

2023-04-25 23:34 UTC, FerCarrilloM approved these changes

2023-04-26 22:38 UTC, FerCarrilloM approved these changes

2023-04-26 22:45 UTC, SebastianSW approved these changes

2023-04-26 23:14 UTC, martinfnsw requested changes
El token de las UT no es válido

2023-04-27 17:50 UTC, martinfnsw approved these changes

2023-04-28 15:20 UTC, SwAeyrton commented
![image](https://user-images.githubusercontent.com/88451104/235187803-f2d6a155-712d-40de-82ea-617af4abbffd.png)
En ValidateResponse falta una propiedad por actualizar

2023-04-28 15:21 UTC, SwAeyrton requested changes
Revisar mi comentario

2023-04-29 00:11 UTC, SwAeyrton approved these changes

2023-05-02 17:18 UTC, merged