Update Readme
lunasoft/SW-sdk-NetStandard pull request #80
Opened 2023-06-01 23:06 UTC by martinfnsw

Update readme

2023-06-01 23:11 UTC, FerCarrilloM approved these changes

2023-06-01 23:15 UTC, SwAeyrton requested changes
Se van a mandar estos cambios desde develop a traves de un release

2023-06-01 23:22 UTC, SwAeyrton approved these changes

2023-06-01 23:49 UTC, marifersw approved these changes

2023-06-02 00:38 UTC, SebastianSW approved these changes

2023-06-02 00:44 UTC, merged