SS-326
lunasoft/SW-sdk-NetStandard pull request #85
Opened 2023-08-08 17:58 UTC by martinfnsw

Clases response a private set

2023-08-08 18:45 UTC, ReyesSW approved these changes

2023-08-08 19:41 UTC, FerCarrilloM approved these changes

2023-08-09 00:24 UTC, SebastianSW approved these changes

2023-08-09 00:43 UTC, SwAeyrton requested changes

2023-08-09 00:43 UTC, SwAeyrton commented on src/sw-sdk/Handlers/ResponseHandlerExtended.cs
> +    internal class ResponseHandlerExtended<TResponse> where TResponse : Response, new()
no es necesario el uso de TResponse, puede quedar de ls siguiente forma sin necesidad de modificar nada mas
`internal T GetExceptionResponse(HttpRequestException ex)
        {
            var r = new T();
            r.SendStatus("error");
            r.SetMessage(ex.Message);
            r.SetMessageDetail(ex.StackTrace);
            return r;
        }`

2023-08-09 00:43 UTC, SwAeyrton commented on src/sw-sdk/Entities/Response.cs
> +        internal void SendStatus(string value)
SetStatus en lugar de sendstatus

2023-08-09 00:43 UTC, SwAeyrton commented on src/sw-sdk/Handlers/ResponseHandlerExtended.cs
> +        internal TResponse GetExceptionRespons<T>(HttpRequestException ex)
falto una e

2023-08-09 15:22 UTC, SwAeyrton approved these changes

2023-08-09 15:25 UTC, merged